/**
 * TypeScript types and interfaces for the P2P Payment Request feature.
 *
 * Feature: 001-payment-request
 * Date: 2026-04-09
 *
 * These types map 1:1 to the Supabase tables / view columns.
 * React Admin resources are typed using these interfaces throughout
 * the application (List, Show, Create components and dataProvider calls).
 */

// =============================================================================
// Status Enum
// =============================================================================

/**
 * All valid values for payment_requests.status.
 * Matches the CHECK constraint in the DB schema.
 */
export const PaymentRequestStatusValues = [
  'pending',
  'paid',
  'declined',
  'cancelled',
  'expired',
] as const;

export type PaymentRequestStatus = (typeof PaymentRequestStatusValues)[number];

// =============================================================================
// Profile
// =============================================================================

/**
 * Maps to the `profiles` table.
 * One row per auth.users entry.
 */
export interface Profile {
  /** UUID — Primary Key, FK → auth.users.id */
  id: string;
  /** User's display name; defaults to email at sign-up */
  display_name: string;
  /** E.164 phone number; nullable; unique */
  phone: string | null;
  /** URL to avatar image; nullable */
  avatar_url: string | null;
  /** ISO 8601 timestamp — row creation time */
  created_at: string;
}

// =============================================================================
// PaymentRequest
// =============================================================================

/**
 * Maps to the `payment_requests` table.
 * Core entity for the P2P payment request feature.
 */
export interface PaymentRequest {
  /** UUID — Primary Key; generated by gen_random_uuid() */
  id: string;
  /** UUID — FK → auth.users.id; the user who created the request */
  sender_id: string;
  /** Email address of the recipient; required; used for resolution */
  recipient_email: string;
  /** E.164 phone number of the recipient; optional */
  recipient_phone: string | null;
  /**
   * UUID — FK → auth.users.id; nullable until the recipient registers.
   * Populated automatically by the resolve_recipient_id trigger.
   */
  recipient_id: string | null;
  /** Amount in the specified currency; must be > 0; max 2 decimal places */
  amount: number;
  /** Currency code; fixed to 'TRY' in v1 */
  currency: 'TRY';
  /** Optional note; max 280 characters */
  note: string | null;
  /** Current lifecycle status of the request */
  status: PaymentRequestStatus;
  /** ISO 8601 timestamp — when the request was created */
  created_at: string;
  /** ISO 8601 timestamp — when the request expires (created_at + 7 days) */
  expires_at: string;
  /**
   * ISO 8601 timestamp — when the request was paid; null until status = 'paid'.
   * Set by the client alongside the status update (dataProvider.update).
   */
  paid_at: string | null;
  /** ISO 8601 timestamp — last time the row was modified */
  updated_at: string;
}

// =============================================================================
// PublicPaymentRequest
// =============================================================================

/**
 * Maps to `public_payment_request_view`.
 * Safe subset of PaymentRequest exposed to anonymous callers.
 * Sensitive fields (sender_id, recipient_email, recipient_phone,
 * recipient_id, paid_at, updated_at) are intentionally omitted.
 */
export interface PublicPaymentRequest {
  id: string;
  amount: number;
  currency: 'TRY';
  note: string | null;
  status: PaymentRequestStatus;
  created_at: string;
  expires_at: string;
}

// =============================================================================
// Form / Create Input
// =============================================================================

/**
 * Input type for the PaymentRequestCreate form.
 * Subset of PaymentRequest with only the user-supplied fields.
 * sender_id is set from the authenticated session, not the form.
 */
export interface PaymentRequestCreateInput {
  recipient_email: string;
  recipient_phone?: string;
  amount: number;
  note?: string;
}

// =============================================================================
// Filter Types (used with dataProvider.getList)
// =============================================================================

/**
 * Filter shape for the Outgoing tab (requests the current user sent).
 */
export interface OutgoingRequestFilter {
  sender_id: string;
  status?: PaymentRequestStatus;
  /** PostgREST ilike filter for email search */
  'recipient_email@ilike'?: string;
}

/**
 * Filter shape for the Incoming tab (requests the current user received).
 */
export interface IncomingRequestFilter {
  recipient_id: string;
  status?: PaymentRequestStatus;
  /** PostgREST ilike filter for email search — searches sender email */
  'sender_email@ilike'?: string;
}

// =============================================================================
// Resource Names
// =============================================================================

/**
 * React Admin resource name constants.
 * Use these instead of string literals to prevent typos.
 */
export const RESOURCE_PAYMENT_REQUESTS = 'payment_requests' as const;
export const RESOURCE_PROFILES = 'profiles' as const;
export const RESOURCE_PUBLIC_VIEW = 'public_payment_request_view' as const;

export type ResourceName =
  | typeof RESOURCE_PAYMENT_REQUESTS
  | typeof RESOURCE_PROFILES
  | typeof RESOURCE_PUBLIC_VIEW;
